### ISSUE TITLE
About the RISC-V Integrated framework

### ISSUE THREAD

**Issue by ariusewy** [UA-RCL/CEDR#4]
Hi,

I noticed your extended CEDR on RISC-V Heterogeneous SoC Design. I wonder if the RISC-V integrated CEDR source code along with the FPGA image is available? I hope to conduct some DSE experiments based on this.

Thank you very much!

**Comment by umutsuluhan** [comment]
Hi, we are working on a release right now and hopefully we will make it public soon. Once we are done with it, I will ping you here.

**Comment by umutsuluhan** [comment]
Hi @ariusewy, 

We have released the source code regarding RISC-V! 

CEDR: https://github.com/UA-RCL/CEDR/tree/hcw-2024
FPGA and Linux Image: https://github.com/UA-RCL/Hardware-Images/tree/riscv-1boom-2big-3little-2fft

You can find the installation instructions in the respective README files in each repository. Please let me know if you have any issues and questions.

**Comment by ariusewy** [comment]
Thank you for your release, I'll have a try!
